# Generated by Django 4.2.1 on 2023-07-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_name_studentprofile_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
