# Generated by Django 4.2.1 on 2023-07-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='institute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profiles.institute'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='rollNumber',
            field=models.CharField(default='', max_length=15),
        ),
    ]
