# Generated by Django 4.2.1 on 2023-07-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_institute_pincode_studentprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
